type WritingProblem = {
  id: string;
};

export const modelAnswers: Record<string, string> = {
  "2級-2023-2-q4": `I think this kind of service will become more common in the future. First, it is very convenient for busy customers. They do not have to wait at home for a delivery, so they can use their time more freely. Second, delivery companies can work more efficiently because drivers can leave packages quickly. It will also reduce missed deliveries. Some people may worry about security, but companies can use photos and special lockers to prevent problems. Therefore, I believe more customers will choose this service.`,
  "2級-2023-3-q4": `I think online interviews are a good idea. First, they are convenient for people who live far from the company. They can join the interview from home, so they do not need to spend much time or money traveling. Second, companies can meet more applicants in a short time. This helps them find talented people from many places. This also reduces stress for everyone. Of course, technical problems may happen, but most people can prepare for them. For these reasons, online interviews are useful.`,
  "2級-2024-1-q4": `Online classes let students far from campus study without long travel, and recorded lessons can be watched repeatedly for better understanding. However, computer or Internet problems may interrupt classes, and students who stay home have fewer chances to meet classmates, which can make them lonely.`,
  "2級-2024-1-q5": `I think the number of movies based on novels will increase. First, novels already have many fans, so movie companies can expect a large audience. This can help them earn income more easily. Second, novels often have interesting characters and stories. Directors can use modern technology to show these worlds clearly on screen. Some movies may not be as good as the original books, but many people still enjoy comparing them. Therefore, more novels will probably be turned into movies.`,
  "2級-2024-2-q4": `Internships help university students learn about companies and jobs that interest them, and they can meet other students who support them. However, very short internships may end before students understand the work well, and joining them can make it harder to keep up with their studies.`,
  "2級-2024-2-q5": `I agree that famous tourist sites should limit the number of visitors. First, too many people can make these places dirty and noisy. If the number of visitors is controlled, castles and temples can be kept clean and beautiful. Second, limits can protect the reputation of tourist sites. Visitors will enjoy them more if they are not extremely crowded. Local shops may worry about losing customers, but a better experience can bring people back. Therefore, visitor limits are a good idea.`,
  "2級-2024-3-q4": `Working abroad allows people to have special experiences and learn a local language through daily life and work, which may help their careers. However, differences in customs can make it hard to adjust to the workplace, and living far from family and friends may cause loneliness.`,
  "2級-2024-3-q5": `I think the number of people who choose such companies will increase. First, many customers now care about the environment, so demand for green products and services is growing. Companies in this field will probably need more workers. Second, people want careers that match their values. Working for an environmentally friendly company can give them strong motivation because they feel they are helping society. Salaries may not always be high at first, but meaningful work is important to many people.`,
  "2級-2025-1-q4": `Young people like social media because it lets them stay connected with friends and discover new ideas outside their community. However, comparing themselves with others may harm their mental health, and sharing personal information or communicating with strangers online can put them in danger when they are not careful.`,
  "2級-2025-1-q5": `I think practicing foreign languages with AI is a good idea. First, AI is very efficient because learners can practice anytime. They do not have to wait for a teacher or partner, and they can repeat difficult parts many times. Second, AI can help learners communicate more confidently by giving quick examples and corrections. It may sometimes make mistakes, so students should also study with books or teachers. However, if they use AI carefully, it can be a useful learning tool.`,
  "2級-2025-2-q4": `Reducing wrapping materials helps the environment by creating less waste and using fewer natural resources. It can also lower producers' costs, making products cheaper. However, goods may be damaged more easily during delivery, and consumers may feel inconvenienced when they must pay for gift wrapping.`,
  "2級-2025-2-q5": `I think setting clear goals when starting new activities is a good idea. First, goals make people more efficient. If they know what they want to achieve, they can choose the best way to spend their time. Second, goals increase motivation. People feel happy when they see their progress, so they can continue even when the activity becomes difficult. They can also measure success more easily. It is also important to stay flexible, but clear goals give people a strong direction at the beginning.`,
  "2級-2025-3-q4": `Customer reviews help shoppers make better choices by providing useful details, and they give companies feedback for improving products. However, some Internet reviews are fake, so people may not know which ones to trust when they shop online. Also, many negative comments can seriously damage small businesses.`,
  "2級-2025-3-q5": `I think providing free online video content for students is a good idea. First, it is convenient because students can study at home whenever they have time. They can also watch the same lesson again if they do not understand it. Second, free videos can make studying more efficient for families because they do not have to pay for extra lessons. This is especially helpful in rural areas. Some videos may be low quality, but students can choose reliable channels. Therefore, this content is helpful.`,

  "3級-2023-2-q4": `Yes, I do. I want to work in Canada because I like English and nature. Also, I can meet many people and learn different cultures there.`,
  "3級-2023-3-q4": `I want to go to an amusement park on my birthday. I like riding roller coasters. Also, I want to eat cake with my friends there.`,
  "3級-2024-1-q4": `Hi James, I saw about fifty pictures at the museum. I stayed there for two hours. Your friend, Taro`,
  "3級-2024-1-q5": `My favorite place to do my homework is my room. It is quiet, so I can study well. Also, I can use my desk there.`,
  "3級-2024-2-q4": `Hi James, The contest was last Sunday. About one hundred people listened to my speech. Your friend, Taro`,
  "3級-2024-2-q5": `Yes, I do. I want to live near a train station because it is convenient. Also, I can go to school and shops easily every day.`,
  "3級-2024-3-q4": `Hi James, I will go there by train. It will start at seven in the evening. Your friend, Taro`,
  "3級-2024-3-q5": `I like December the best. My birthday is in December, so I feel excited. Also, I can enjoy Christmas with my family and eat special food.`,
  "3級-2025-1-q4": `Hi James, I planted the potatoes in April. I am growing ten carrots now. Your friend, Taro`,
  "3級-2025-1-q5": `English is more interesting for me. I can learn about many countries through English. Also, I like talking with foreign people when I travel abroad.`,
  "3級-2025-2-q4": `Hi James, I bought the present at a bookstore. I will give it to him tomorrow. Your friend, Taro`,
  "3級-2025-2-q5": `I like to eat rice balls when I am tired. They are easy to eat. Also, they give me energy after club activities at school.`,
  "3級-2025-3-q4": `Hi James, I will give my sister a bag. I will invite six people to the party. Your friend, Taro`,
  "3級-2025-3-q5": `Yes, I do. I like eating vegetables because they are healthy. Also, my mother makes delicious salads and soup with many vegetables for my family.`,

  "準1級-2023-2-q4": `I believe companies should be required to produce goods that are easy to recycle. First, such products would reduce the amount of waste sent to landfills. Many items are thrown away because they contain different materials that are difficult to separate. If companies designed them for recycling from the beginning, more resources could be reused. Second, clear rules would encourage innovation. Companies would compete to create simpler packaging and longer-lasting products, and this could improve their public image. These rules could also make consumers more aware of recycling. When products are easier to sort, people are more likely to participate. Some firms may complain about higher costs, but society should not leave environmental damage to future generations. Therefore, governments should require companies to make recyclable goods.`,
  "準1級-2024-1-q4": `Some countries now provide free lunches to all students, not only limited groups. Supporters say healthy meals improve concentration and test results, and they also help busy parents save time for work and child care. However, critics argue that schools must prepare many meals every day, and uneaten food creates a large amount of waste, and this can be expensive for schools.`,
  "準1級-2024-1-q5": `I think the government should encourage vacant land in urban areas to be used for farming. First, city farms can make good use of land that would otherwise be left empty. They can provide fresh vegetables to local residents and reduce the distance food travels. This helps lower pollution from transportation. Second, urban farming can strengthen communities. People of different ages can work together, learn about food, and share the harvest. Schools and local restaurants could also use the crops, which would make the projects more useful for the whole neighborhood. Some vacant land may be needed for housing or shops, so each area should be considered carefully. However, when land is unused for a long time, farming is a practical and beneficial choice.`,
  "準1級-2024-2-q4": `Some people want governments to fund private companies' space exploration. Supporters say this could create new technology useful to ordinary consumers and speed up discoveries by involving more scientists. However, critics worry that old space laws are unclear for private firms, so companies might claim parts of space as their own before clear and fair rules are created for everyone involved.`,
  "準1級-2024-2-q5": `I do not think a high salary should be the most important thing when searching for a job. Of course, money matters because people need to pay for housing, food, and education. However, working conditions are also important. If employees work extremely long hours or feel too much stress, they may lose their health even if they earn a lot. Another key factor is personal growth. A job that teaches useful skills can lead to better opportunities in the future. A supportive workplace can also make employees more creative and loyal, which benefits both workers and companies over time. People should also think about whether the work is meaningful to them. For these reasons, salary should be only one of several points to consider.`,
  "準1級-2024-3-q4": `Solar radiation modification is a proposed method for reducing global warming by reflecting sunlight away from Earth. Supporters say it could quickly lower temperatures and help industries in hot countries, such as agriculture and tourism. However, critics worry that the chemicals used may affect weather or nature, and SRM cannot solve other problems caused by CO2 emissions because fossil fuels would still be burned.`,
  "準1級-2024-3-q5": `I believe people should be banned from keeping dangerous animals as pets. The main reason is safety. Even careful owners may not be able to control large or poisonous animals all the time. If such an animal escapes, neighbors and children could be seriously harmed. Another reason is animal welfare. Dangerous animals often need special food, space, and environments that ordinary homes cannot provide. Keeping them as pets may cause stress or illness. In addition, endangered species may be taken from nature for the pet trade. A ban could help protect them more effectively. Some people may say they should have freedom of choice, but that freedom should be limited when it creates serious risks for others. Therefore, a ban is necessary.`,
  "準1級-2025-1-q4": `District heating connects many buildings to one central energy source. Supporters say it uses less energy than separate heating systems, reducing CO2 emissions, and it is reliable because the systems are regularly checked and maintained. However, critics argue that installing underground pipes in built-up areas requires major construction, making the system very expensive for communities to introduce and difficult to complete quickly.`,
  "準1級-2025-1-q5": `I believe governments should work together to increase global food production. The world population is still growing, and some regions already suffer from food shortages. If countries share agricultural technology, farmers can grow more food even with limited land. For example, better seeds and irrigation systems can raise crop yields. Cooperation is also important because food problems do not stop at national borders. Climate change and pollution can damage farms in many countries, so governments need common rules to protect the environment while producing enough food. Rich countries could support poor countries by sharing research and training. This would make the world more stable and fair. Some countries may want to act alone, but international cooperation would be more effective. Therefore, governments should address food production together.`,
  "準1級-2025-2-q4": `Some countries want to ban farmers from burning stubble left after harvests. Supporters say this would protect people's health by preventing harmful smoke from spreading to both rural and urban areas and would maintain soil quality by saving useful organisms. However, opponents worry that removing stubble without fire requires expensive machines that many farmers cannot afford, especially in poorer farming communities.`,
  "準1級-2025-2-q5": `I do not think people who live in cities should be required to use public transportation. Public transportation can reduce pollution and traffic accidents, so governments should certainly improve trains and buses. However, making it a requirement would be unfair to some residents. Parents with small children, people with disabilities, and workers who travel late at night may need cars for safety or convenience. In addition, public systems can be crowded or delayed, which makes daily life stressful. Cities can also create bicycle lanes and safe walking areas. These choices would reduce car use without removing personal freedom. A better policy would be to make public transportation cheaper, cleaner, and more reliable so that people choose it willingly. Therefore, encouragement is better than a strict rule.`,
  "準1級-2025-3-q4": `Biologgers are electronic devices attached to animals to collect data. Supporters say they let scientists study animals that live in difficult places or avoid humans. However, critics say the data may be unreliable because devices can stress animals. The devices' size and weight may also make feeding or escaping harder, which could lead to early death and harm the research subjects themselves.`,
  "準1級-2025-3-q5": `I think self-driving cars should be allowed to drive on public roads, but only under strict rules. They may improve safety because computers do not get tired or distracted like human drivers. They could also make transportation more convenient for elderly people and those who cannot drive. However, there are serious concerns about responsibility. If an accident happens, it may be unclear whether the owner, the maker, or the software developer is responsible. Also, some driving jobs may disappear. Public roads should include limited areas at first, so engineers can collect real data and improve systems before wider use. For these reasons, governments should test the technology carefully, require clear safety standards, and introduce it gradually. With proper rules, self-driving cars can be useful.`,

  "準2級-2023-2-q5": `I think it is good for students to make study plans for their summer vacations. First, plans help students use their time well. They can study every day and still enjoy free time. Second, students can finish their homework earlier. Then, they will not feel nervous at the end of vacation.`,
  "準2級-2024-1-q5": `Hi Alex, Your visit sounds nice. How large was the library? How many books did it have? I think such cafes will become popular because people can relax and study in the same place. It is very convenient. Your friend, Taro`,
  "準2級-2024-1-q6": `I think it is a good idea for students to get up early to study in the morning. First, the morning is quiet, so students can concentrate well. Second, studying before school gives them more free time after school. They can relax or join club activities without worrying too much.`,
  "準2級-2024-2-q5": `Hi Alex, That sounds exciting. Where was the new stadium? How many people can watch games there? I think more people will watch rugby because big stadiums make games exciting. Also, people can learn the rules on TV. Your friend, Taro`,
  "準2級-2024-2-q6": `I think it is a good idea for smartphone users to have a tablet PC. First, the screen is bigger, so it is easier to read articles and watch videos. Second, tablets are useful for studying or working. People can take notes and check websites more comfortably than on a smartphone.`,
  "準2級-2024-3-q5": `Hi Alex, Your trip sounds wonderful. How many cities did you visit on the tour? What food did you like best? I do not think such a break will become popular in Japan because many workers and customers are too busy. Your friend, Taro`,
  "準2級-2024-3-q6": `I think families should make time to play sports together. First, sports help family members stay healthy. They can exercise while having fun. Second, playing sports gives families more chances to talk. Even busy parents and children can enjoy a short game together on weekends. This can make their relationships stronger.`,
  "準2級-2025-1-q5": `Hi Alex, That sounds fun. How long did you ride the boat? Who drove it on the lake? I think more people will enjoy bird watching because it is relaxing and people can do it in many places. Your friend, Taro`,
  "準2級-2025-1-q6": `I do not think it is good for children to decide what time they go to bed every day. First, many children may stay up too late. Then, they cannot study well the next day. Second, enough sleep is important for their health, so parents should help them keep good habits.`,
  "準2級-2025-2-q5": `Hi Alex, The sports center sounds nice. How many people were using it? What sport did you enjoy there? I think such pools will increase because people can swim all year. They are useful for health and exercise. Your friend, Taro`,
  "準2級-2025-2-q6": `I think it is a good idea for people to take notes on their smartphones. First, smartphones are easy to carry, so people can write ideas anywhere. Second, they can search their notes quickly later. Paper notebooks are useful too, but smartphones are more convenient in daily life. For these reasons, I support this idea.`,
  "準2級-2025-3-q5": `Hi Alex, Your new city sounds interesting. How far is it from your old home? What shopping mall do you like there? I think more cities will provide free buses because many elderly people need easy transportation. Your friend, Taro`,
  "準2級-2025-3-q6": `I think it is good for students to share their opinions about books with their friends. First, they can learn different ideas from each other. Second, talking about books makes reading more interesting. If students enjoy reading more, they may read many kinds of books by themselves. This is good for their studies.`,
};

export function countAnswerWords(answer: string) {
  return answer.match(/[A-Za-z0-9]+(?:[-'][A-Za-z0-9]+)*/g)?.length ?? 0;
}

export function getModelAnswer(problem: WritingProblem) {
  return (
    modelAnswers[problem.id] ??
    "This sample answer has not been prepared for this problem yet."
  );
}
